<a href="https://colab.research.google.com/github/venus751/Hello--world/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

creating a 1 dim array

In [5]:
a = np.array([1, 2, 3, 4])
print(a)


[1 2 3 4]


(4,)

In [6]:
a.shape

(4,)

In [7]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
b.shape

(2, 4)

In [10]:
c = np.array([(1, 2,3,4), (5, 6, 7, 8)],dtype =float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholder in numpy arrays

In [11]:
#create a numpy arrays of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#create a numpy arrays with values of one
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#create array of a particular value
z = np.full((5,4),8)
print(z)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [20]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
# create a numpy array with random value

#np.random.random() is one of the most fundamental building blocks in all of machine learning.
#Every time a neural network is trained anywhere in the world — whether it is diagnosing cancer,
#detecting fraud, translating languages, or recognising faces,
# a random NumPy array was the very first thing generated before any learning began.

b = np.random.random((4,3))
print(b)

[[0.34477074 0.86734092 0.05301047]
 [0.9925469  0.00489021 0.92411473]
 [0.60587257 0.28789982 0.35728456]
 [0.76838006 0.31084715 0.382764  ]]


In [25]:
#random integer value array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[11 56 98 31 46]
 [93 16 26 89 76]
 [95 60 25 69 10]]


In [27]:
#create an array of evenly spaced values
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [33]:
#create an array of evenly spaced value...>Specifying the step
e = np.arange(10,30,6)
print(e)

[10 16 22 28]


In [35]:
#convert a list to a numpy array
list1 =[10,20,20,20,50]
np_array =np.asarray(list1)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [36]:
c= np.random.randint(10,90,(5,5))
print(c)

[[18 21 85 13 29]
 [61 85 83 46 80]
 [25 48 81 31 28]
 [39 10 52 88 62]
 [62 40 67 70 62]]


In [37]:
#array dimension
print(c.shape)

(5, 5)


In [40]:
#num of dimension
print(c.ndim)

2
2


In [41]:
#num of element in an array
print(c.size)

25
25


In [43]:
#checking the datatype of the value in the array
print(c.dtype)

int64
int64


Mathematical Operation in np array

In [44]:
# comparing list mathematical operation with numpy

list1 = [1,2,3,4,5]
list2 =[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [51]:
a =np.random.randint(0,10,(3,3))
b =np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a/b)
print(a*b)



[[4 0 1]
 [3 6 8]
 [3 4 1]]
[[13 19 12]
 [10 11 18]
 [19 19 14]]
[[17 19 13]
 [13 17 26]
 [22 23 15]]
[[ -9 -19 -11]
 [ -7  -5 -10]
 [-16 -15 -13]]
[[0.30769231 0.         0.08333333]
 [0.3        0.54545455 0.44444444]
 [0.15789474 0.21052632 0.07142857]]
[[ 52   0  12]
 [ 30  66 144]
 [ 57  76  14]]


Array Manipulation

In [52]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 1 5]
 [4 9 9]]
(2, 3)


In [53]:
#transpose of array
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 4]
 [1 9]
 [5 9]]
(3, 2)


In [54]:
#alternative
trans2=array.T
print(trans2)
print(trans2.shape)

[[5 4]
 [1 9]
 [5 9]]
(3, 2)


In [55]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 9 7]
 [9 2 2]]
(2, 3)


In [56]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 9]
 [7 9]
 [2 2]]
(3, 2)
